LOS_IDX = {
    "SOD": 0,
    "CONST": 1,
    "PRN": 2,
    "ELEV": 3,
    "AZIM": 4,
    "SAT-X": 5,
    "SAT-Y": 6,
    "SAT-Z": 7,
    "SAT-VX": 8,
    "SAT-VY": 9,
    "SAT-VZ": 10,
    "MEASUREMENT": 11,
    "GEOM-RANGE": 12,
    "RANGE-RATE": 13,
    "SIS-ERR": 14,
    "IONO-ERR": 15,
    "TROPO-ERR": 16,
    "LOCAL-ERR": 17,
    "RANGE-ERR": 18,
}

POS_IDX = {
    "SOD": 0,
    "LONEST": 1,
    "LATEST": 2,
    "ALTEST": 3,
    "CLKEST": 4,
    "NSV": 5,
    "HPE": 6,
    "VPE": 7,
    "NPE": 8,
    "EPE": 9,
    "DPE": 10,
    "GDOP": 11,
    "PDOP": 12,
    "TDOP": 13,
}
